import json
import requests


def main():
    base = "http://localhost:8000"
    # Fetch the relevant tool
    tools = requests.get(base + "/tool_search?query=solana").json()

    # Define the agent workflow
    agents_config = {
        "solana_agent": {
            "role": "Solana Blockchain Assistant",
            "goal": "You are an assistant that interacts with the Solana blockchain. You can perform actions like checking token balances, fetching prices, and more",
            "backstory": "A solana blockchain assistant with access to various tools for performing actions",
            # We must pass the tools by id
            "agent_tools": [
                tool["id"]
                for tool in tools
                if tool["payload"]["id"].startswith("Solana")
            ],
        },
    }
    tasks_config = {
        "solana_task": {
            "description": "{query}",
            "expected_output": "A response to the query generated by calling the relevant functions",
            "agent": "solana_agent",
        },
    }

    agent = requests.post(
        base + "/save_agent",
        json={
            "name": "Solana Blockchain Agent",
            "description": "Agent to interact with the Solana Blockchain",
            "arguments": ["query"],
            "agents": agents_config,
            "tasks": tasks_config,
        },
    ).json()

    print("Saved agent with ID", agent["agent_id"])

    response = requests.get(
        base + "/agent_call?agent_id=" + agent["agent_id"],
        json={
            "query": "Trade 1 qty to token CZgCjLLrr62jkCzf9bFYD3n8dQbTtpQ9B5NDuXxVeGU4 with 50 bps slippage",
        },
    ).json()
    print(response)


main()
