name: Publish Docker Image

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Derive image tags
        id: meta
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            VERSION_TAG=${GITHUB_REF_NAME}
          else
            SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
            VERSION_TAG=sha-${SHORT_SHA}
          fi
          echo "version_tag=${VERSION_TAG}" >> $GITHUB_OUTPUT

      - name: Login to Vistara Registry (no-auth public)
        run: |
          echo "Registry is public/no-auth; skipping docker login"

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.prod
          platforms: linux/amd64
          push: true
          tags: |
            registry.vistara.dev/z-framework:latest
            registry.vistara.dev/z-framework:${{ steps.meta.outputs.version_tag }}
          cache-from: type=registry,ref=registry.vistara.dev/z-framework:buildcache
          cache-to: type=registry,ref=registry.vistara.dev/z-framework:buildcache,mode=max


